#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

echo "the pre-commit hook ran 🚀"
echo "prettify running on staged files 🚀"
npx pretty-quick --staged # ✅ replace the dummy "echo" command
echo "the pre-commit hook ran 🚀" 
